# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\leonardo\Documents\Proyectos UNEFA\GYM\gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(800, 600))
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_login = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page_login.sizePolicy().hasHeightForWidth())
        self.page_login.setSizePolicy(sizePolicy)
        self.page_login.setMaximumSize(QtCore.QSize(800, 600))
        self.page_login.setObjectName("page_login")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.page_login)
        self.horizontalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.widget_baner = QtWidgets.QWidget(self.page_login)
        self.widget_baner.setMinimumSize(QtCore.QSize(800, 600))
        self.widget_baner.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.widget_baner.setObjectName("widget_baner")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_baner)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_baner = QtWidgets.QLabel(self.widget_baner)
        self.label_baner.setMinimumSize(QtCore.QSize(400, 600))
        self.label_baner.setStyleSheet("background-image: url(:/baner/recursos/baner.jpg);\n"
"\n"
"")
        self.label_baner.setText("")
        self.label_baner.setScaledContents(False)
        self.label_baner.setObjectName("label_baner")
        self.horizontalLayout_2.addWidget(self.label_baner)
        self.widget_login = QtWidgets.QWidget(self.widget_baner)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_login.sizePolicy().hasHeightForWidth())
        self.widget_login.setSizePolicy(sizePolicy)
        self.widget_login.setMaximumSize(QtCore.QSize(16777215, 550))
        self.widget_login.setStyleSheet("QWidget{\n"
"    border: 2px solid rgb(26, 70, 141);\n"
"    border-radius: 20px;\n"
"\n"
"}\n"
"\n"
"#btn_facebook , #btn_in , #btn_twitter , #btn_instagram{\n"
"    \n"
"    \n"
"\n"
"    border:none;\n"
"    color: rgb(26, 70, 141)\n"
"\n"
"}\n"
"\n"
"")
        self.widget_login.setObjectName("widget_login")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.widget_login)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.widget_3 = QtWidgets.QWidget(self.widget_login)
        self.widget_3.setStyleSheet("border:none")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_20.setContentsMargins(-1, 20, -1, 0)
        self.verticalLayout_20.setSpacing(7)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_3 = QtWidgets.QLabel(self.widget_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(24)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("#label_3{border:none;\n"
"color:  rgb(26, 70, 141);\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"border-radius: 0px;}\n"
"\n"
"\n"
"\n"
"#label_3:hover{\n"
"\n"
"margin: 5px;\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(26, 70, 141, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_20.addWidget(self.label_3)
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("border:none;\n"
"\n"
"color:  rgb(26, 70, 141);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_20.addWidget(self.label_2)
        self.verticalLayout_24.addWidget(self.widget_3)
        self.widget_4 = QtWidgets.QWidget(self.widget_login)
        self.widget_4.setStyleSheet("border:none;")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_21.setContentsMargins(11, 11, -1, -1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit.setInputMask("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_21.addWidget(self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setMaxLength(6)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_21.addWidget(self.lineEdit_2)
        self.pushButton = QtWidgets.QPushButton(self.widget_4)
        self.pushButton.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_21.addWidget(self.pushButton)
        self.verticalLayout_24.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_login)
        self.widget_5.setMaximumSize(QtCore.QSize(16777215, 55))
        self.widget_5.setStyleSheet("border:none\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_19.setContentsMargins(60, -1, 60, -1)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.btn_facebook = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Icons Social Media 8")
        font.setPointSize(20)
        self.btn_facebook.setFont(font)
        self.btn_facebook.setStyleSheet("#btn_facebook:hover{\n"
"font-size: 20px;\n"
"\n"
"}\n"
"")
        self.btn_facebook.setObjectName("btn_facebook")
        self.horizontalLayout_19.addWidget(self.btn_facebook)
        self.btn_twitter = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Icons Social Media 8")
        font.setPointSize(20)
        self.btn_twitter.setFont(font)
        self.btn_twitter.setStyleSheet("#btn_twitter:hover{\n"
"\n"
"\n"
"font-size: 20px;\n"
"\n"
"}\n"
"\n"
"")
        self.btn_twitter.setObjectName("btn_twitter")
        self.horizontalLayout_19.addWidget(self.btn_twitter)
        self.btn_instagram = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Icons Social Media 8")
        font.setPointSize(20)
        font.setItalic(False)
        self.btn_instagram.setFont(font)
        self.btn_instagram.setStyleSheet("#btn_instagram:hover{\n"
"\n"
"font-size: 20px;\n"
"\n"
"}\n"
"")
        self.btn_instagram.setObjectName("btn_instagram")
        self.horizontalLayout_19.addWidget(self.btn_instagram)
        self.btn_in = QtWidgets.QPushButton(self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Icons Social Media 8")
        font.setPointSize(20)
        self.btn_in.setFont(font)
        self.btn_in.setStyleSheet("#btn_in:hover{\n"
"\n"
"font-size: 20px;\n"
"\n"
"}\n"
"")
        self.btn_in.setObjectName("btn_in")
        self.horizontalLayout_19.addWidget(self.btn_in)
        self.verticalLayout_24.addWidget(self.widget_5)
        self.verticalLayout_24.setStretch(0, 2)
        self.verticalLayout_24.setStretch(1, 4)
        self.verticalLayout_24.setStretch(2, 1)
        self.horizontalLayout_2.addWidget(self.widget_login)
        self.horizontalLayout_20.addWidget(self.widget_baner)
        self.stackedWidget.addWidget(self.page_login)
        self.page_main = QtWidgets.QWidget()
        self.page_main.setObjectName("page_main")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.page_main)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bar_menu = QtWidgets.QWidget(self.page_main)
        self.bar_menu.setStyleSheet("background-color: rgb(26, 70, 141);")
        self.bar_menu.setObjectName("bar_menu")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.bar_menu)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_logo = QtWidgets.QLabel(self.bar_menu)
        self.label_logo.setMaximumSize(QtCore.QSize(250, 44))
        font = QtGui.QFont()
        font.setFamily("Broadway")
        font.setPointSize(20)
        font.setUnderline(True)
        self.label_logo.setFont(font)
        self.label_logo.setStyleSheet("#label_logo{\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"margin-left: 1px;\n"
"\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"#label_logo:hover{\n"
"\n"
"margin: 5px;\n"
"color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 174, 225, 255), stop:1 rgba(255, 255, 255, 255));\n"
"\n"
"\n"
"\n"
"}\n"
"\n"
"\n"
"\n"
"")
        self.label_logo.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_logo.setObjectName("label_logo")
        self.horizontalLayout.addWidget(self.label_logo)
        self.bar_btn = QtWidgets.QFrame(self.bar_menu)
        self.bar_btn.setStyleSheet("#bar_btn{\n"
"margin:10px;\n"
"}\n"
"\n"
"QPushButton{\n"
"    \n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(0, 0, 0,0);\n"
"\n"
"\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(0, 0, 0,0);\n"
"border-bottom: 2px solid rgb(255, 255, 255) ;\n"
"\n"
"}\n"
"")
        self.bar_btn.setObjectName("bar_btn")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.bar_btn)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_inicio = QtWidgets.QPushButton(self.bar_btn)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_inicio.setFont(font)
        self.btn_inicio.setStyleSheet("")
        self.btn_inicio.setObjectName("btn_inicio")
        self.horizontalLayout_4.addWidget(self.btn_inicio)
        self.bnt_registro = QtWidgets.QPushButton(self.bar_btn)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.bnt_registro.setFont(font)
        self.bnt_registro.setObjectName("bnt_registro")
        self.horizontalLayout_4.addWidget(self.bnt_registro)
        self.btn_pos = QtWidgets.QPushButton(self.bar_btn)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pos.setFont(font)
        self.btn_pos.setObjectName("btn_pos")
        self.horizontalLayout_4.addWidget(self.btn_pos)
        self.btn_pos_2 = QtWidgets.QPushButton(self.bar_btn)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_pos_2.setFont(font)
        self.btn_pos_2.setStyleSheet("margin-right: 3px;")
        self.btn_pos_2.setObjectName("btn_pos_2")
        self.horizontalLayout_4.addWidget(self.btn_pos_2)
        self.bnt_config = QtWidgets.QPushButton(self.bar_btn)
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bnt_config.setFont(font)
        self.bnt_config.setObjectName("bnt_config")
        self.horizontalLayout_4.addWidget(self.bnt_config)
        self.horizontalLayout.addWidget(self.bar_btn)
        self.verticalLayout.addWidget(self.bar_menu)
        self.page_option = QtWidgets.QStackedWidget(self.page_main)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.page_option.setFont(font)
        self.page_option.setStyleSheet("")
        self.page_option.setObjectName("page_option")
        self.page_inicio = QtWidgets.QWidget()
        self.page_inicio.setStyleSheet("background-color: rgb(236, 240, 252)")
        self.page_inicio.setObjectName("page_inicio")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.page_inicio)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_9 = QtWidgets.QFrame(self.page_inicio)
        self.frame_9.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_9.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"")
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.container = QtWidgets.QWidget(self.frame_9)
        self.container.setStyleSheet("QLabel {\n"
"\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.container.setObjectName("container")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.container)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.item_1 = QtWidgets.QWidget(self.container)
        self.item_1.setMinimumSize(QtCore.QSize(120, 80))
        self.item_1.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 209, 71);\n"
"}\n"
"\n"
"")
        self.item_1.setObjectName("item_1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.item_1)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_36 = QtWidgets.QLabel(self.item_1)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("")
        self.label_36.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_36.setObjectName("label_36")
        self.verticalLayout_10.addWidget(self.label_36)
        self.label_37 = QtWidgets.QLabel(self.item_1)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.verticalLayout_10.addWidget(self.label_37)
        self.horizontalLayout_18.addWidget(self.item_1)
        self.item_2 = QtWidgets.QWidget(self.container)
        self.item_2.setMinimumSize(QtCore.QSize(120, 80))
        self.item_2.setStyleSheet("background-color: rgb(58, 120, 255);\n"
"")
        self.item_2.setObjectName("item_2")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.item_2)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.label_38 = QtWidgets.QLabel(self.item_2)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("")
        self.label_38.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_38.setObjectName("label_38")
        self.verticalLayout_13.addWidget(self.label_38)
        self.label_39 = QtWidgets.QLabel(self.item_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.verticalLayout_13.addWidget(self.label_39)
        self.horizontalLayout_18.addWidget(self.item_2)
        self.item_4 = QtWidgets.QWidget(self.container)
        self.item_4.setMinimumSize(QtCore.QSize(120, 80))
        self.item_4.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.item_4.setObjectName("item_4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.item_4)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.label_40 = QtWidgets.QLabel(self.item_4)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("")
        self.label_40.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_40.setObjectName("label_40")
        self.verticalLayout_14.addWidget(self.label_40)
        self.label_41 = QtWidgets.QLabel(self.item_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.verticalLayout_14.addWidget(self.label_41)
        self.horizontalLayout_18.addWidget(self.item_4)
        self.item_3 = QtWidgets.QWidget(self.container)
        self.item_3.setMinimumSize(QtCore.QSize(120, 80))
        self.item_3.setStyleSheet("background-color: rgb(22, 226, 0);")
        self.item_3.setObjectName("item_3")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.item_3)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_42 = QtWidgets.QLabel(self.item_3)
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("")
        self.label_42.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_42.setObjectName("label_42")
        self.verticalLayout_15.addWidget(self.label_42)
        self.label_43 = QtWidgets.QLabel(self.item_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.verticalLayout_15.addWidget(self.label_43)
        self.horizontalLayout_18.addWidget(self.item_3)
        self.verticalLayout_16.addWidget(self.container)
        self.tableWidget = QtWidgets.QTableWidget(self.frame_9)
        self.tableWidget.setEditTriggers(QtWidgets.QTableWidget.EditTrigger.NoEditTriggers)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Box)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(120)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(True)
        self.tableWidget.verticalHeader().setSortIndicatorShown(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_16.addWidget(self.tableWidget)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.frame_9)
        self.lineEdit_15.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_15.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_15.setFont(font)
        self.lineEdit_15.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_15.setInputMask("")
        self.lineEdit_15.setMaxLength(10)
        self.lineEdit_15.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_11.addWidget(self.lineEdit_15)
        self.btn_cliente_7 = QtWidgets.QPushButton(self.frame_9)
        self.btn_cliente_7.setMinimumSize(QtCore.QSize(100, 30))
        self.btn_cliente_7.setMaximumSize(QtCore.QSize(16777214, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_7.setFont(font)
        self.btn_cliente_7.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_7.setObjectName("btn_cliente_7")
        self.horizontalLayout_11.addWidget(self.btn_cliente_7)
        self.verticalLayout_16.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_13.addWidget(self.frame_9)
        self.page_option.addWidget(self.page_inicio)
        self.page_registro = QtWidgets.QWidget()
        self.page_registro.setStyleSheet("background-color: rgb(236, 240, 252)")
        self.page_registro.setObjectName("page_registro")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.page_registro)
        self.horizontalLayout_9.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.page_registro)
        self.frame_6.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_6.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"")
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_7 = QtWidgets.QFrame(self.frame_6)
        self.frame_7.setStyleSheet("/*#frame_2{\n"
"border: 2px solid rgb(26,70,141);\n"
"\n"
"}*/\n"
"")
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_7.setContentsMargins(200, 20, 200, 20)
        self.verticalLayout_7.setSpacing(6)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_21 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.verticalLayout_7.addWidget(self.label_21)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_11.setInputMask("")
        self.lineEdit_11.setMaxLength(30)
        self.lineEdit_11.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.verticalLayout_7.addWidget(self.lineEdit_11)
        self.label_22 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.verticalLayout_7.addWidget(self.label_22)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"paddin-right: 100px;\n"
"\n"
"")
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setMaxLength(30)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_7.addWidget(self.lineEdit_4)
        self.label_23 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.verticalLayout_7.addWidget(self.label_23)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_8.setInputMask("")
        self.lineEdit_8.setMaxLength(30)
        self.lineEdit_8.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.verticalLayout_7.addWidget(self.lineEdit_8)
        self.label_24 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.verticalLayout_7.addWidget(self.label_24)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setMaxLength(30)
        self.lineEdit_6.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_7.addWidget(self.lineEdit_6)
        self.label_25 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.verticalLayout_7.addWidget(self.label_25)
        self.textEdit_2 = QtWidgets.QTextEdit(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("border: 1px solid rgb(26,70,141);\n"
"color:rgb(26, 70, 141);")
        self.textEdit_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.textEdit_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setDocumentTitle("")
        self.textEdit_2.setObjectName("textEdit_2")
        self.verticalLayout_7.addWidget(self.textEdit_2)
        self.verticalLayout_6.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_6)
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_8.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_8.setSpacing(30)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.btn_cliente_5 = QtWidgets.QPushButton(self.frame_8)
        self.btn_cliente_5.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_5.setFont(font)
        self.btn_cliente_5.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_5.setObjectName("btn_cliente_5")
        self.horizontalLayout_8.addWidget(self.btn_cliente_5)
        self.btn_cliente_6 = QtWidgets.QPushButton(self.frame_8)
        self.btn_cliente_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_6.setFont(font)
        self.btn_cliente_6.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_6.setObjectName("btn_cliente_6")
        self.horizontalLayout_8.addWidget(self.btn_cliente_6)
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_8)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_8.addWidget(self.pushButton_6)
        self.verticalLayout_6.addWidget(self.frame_8)
        self.verticalLayout_6.setStretch(0, 5)
        self.verticalLayout_6.setStretch(1, 1)
        self.horizontalLayout_9.addWidget(self.frame_6)
        self.page_option.addWidget(self.page_registro)
        self.page_pos = QtWidgets.QWidget()
        self.page_pos.setStyleSheet("background-color: rgb(236, 240, 252)")
        self.page_pos.setObjectName("page_pos")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.page_pos)
        self.horizontalLayout_3.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_pos_container = QtWidgets.QFrame(self.page_pos)
        self.frame_pos_container.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_pos_container.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"")
        self.frame_pos_container.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_pos_container.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_pos_container.setObjectName("frame_pos_container")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_pos_container)
        self.horizontalLayout_16.setContentsMargins(20, 9, 20, -1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_17 = QtWidgets.QFrame(self.frame_pos_container)
        self.frame_17.setStyleSheet("#label_27 , #label_28 , #label_31  {\n"
"background-color: rgb(236, 240, 252)\n"
"\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_10 = QtWidgets.QFrame(self.frame_17)
        self.frame_10.setStyleSheet("#frame_10{\n"
"    border-bottom: 1px solid rgba(26, 70, 141, 150);\n"
"    border-right: 1px solid rgba(26, 70, 141, 150);\n"
"}\n"
"\n"
"")
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_12 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_8.addWidget(self.label_12)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_12.setInputMask("")
        self.lineEdit_12.setMaxLength(10)
        self.lineEdit_12.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.verticalLayout_8.addWidget(self.lineEdit_12)
        self.label_26 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.verticalLayout_8.addWidget(self.label_26)
        self.label_27 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet("padding-left:2px;\n"
"color:rgb(26, 70, 141);")
        self.label_27.setObjectName("label_27")
        self.verticalLayout_8.addWidget(self.label_27)
        self.label_29 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.verticalLayout_8.addWidget(self.label_29)
        self.label_28 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_28.setFont(font)
        self.label_28.setStyleSheet("padding-left:2px;\n"
"color:rgb(26, 70, 141);")
        self.label_28.setObjectName("label_28")
        self.verticalLayout_8.addWidget(self.label_28)
        self.label_30 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.verticalLayout_8.addWidget(self.label_30)
        self.label_31 = QtWidgets.QLabel(self.frame_10)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_31.setFont(font)
        self.label_31.setStyleSheet("padding-left:2px;\n"
"color:rgb(26, 70, 141);")
        self.label_31.setObjectName("label_31")
        self.verticalLayout_8.addWidget(self.label_31)
        self.verticalLayout_12.addWidget(self.frame_10)
        self.frame_16 = QtWidgets.QFrame(self.frame_17)
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_10.setContentsMargins(100, -1, 100, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btn_cliente_4 = QtWidgets.QPushButton(self.frame_16)
        self.btn_cliente_4.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_4.setFont(font)
        self.btn_cliente_4.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_4.setObjectName("btn_cliente_4")
        self.horizontalLayout_10.addWidget(self.btn_cliente_4)
        self.verticalLayout_12.addWidget(self.frame_16)
        self.verticalLayout_12.setStretch(0, 5)
        self.verticalLayout_12.setStretch(1, 2)
        self.horizontalLayout_16.addWidget(self.frame_17)
        self.frame_19 = QtWidgets.QFrame(self.frame_pos_container)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(6)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_14 = QtWidgets.QFrame(self.frame_19)
        self.frame_14.setStyleSheet("#frame_14{\n"
"/*    border-left: 1px solid rgba(26, 70, 141, 150);*/\n"
"    border-bottom: 1px solid rgba(26, 70, 141, 150);\n"
"}\n"
"")
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_32 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.verticalLayout_9.addWidget(self.label_32)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_13.setFont(font)
        self.lineEdit_13.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_13.setInputMask("")
        self.lineEdit_13.setMaxLength(2)
        self.lineEdit_13.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_13.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.verticalLayout_9.addWidget(self.lineEdit_13)
        self.label_34 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_9.addWidget(self.label_34)
        self.label_33 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.verticalLayout_9.addWidget(self.label_33)
        self.label_35 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.verticalLayout_9.addWidget(self.label_35)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.frame_14)
        self.lineEdit_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_14.setInputMask("")
        self.lineEdit_14.setMaxLength(3)
        self.lineEdit_14.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_14.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.verticalLayout_9.addWidget(self.lineEdit_14)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(0, 0, 12, 0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_47 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_14.addWidget(self.label_47)
        self.label_48 = QtWidgets.QLabel(self.frame_14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_48.setObjectName("label_48")
        self.horizontalLayout_14.addWidget(self.label_48)
        self.verticalLayout_9.addLayout(self.horizontalLayout_14)
        self.widget_2 = QtWidgets.QWidget(self.frame_14)
        self.widget_2.setStyleSheet("#widget_2 {\n"
"    background-color: rgb(26,70,141);\n"
"}\n"
"#label_62 , #label_63 {\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(26,70,141);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_63 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_63.setFont(font)
        self.label_63.setObjectName("label_63")
        self.horizontalLayout_15.addWidget(self.label_63)
        self.label_62 = QtWidgets.QLabel(self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_62.setFont(font)
        self.label_62.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_62.setObjectName("label_62")
        self.horizontalLayout_15.addWidget(self.label_62)
        self.verticalLayout_9.addWidget(self.widget_2)
        self.verticalLayout_11.addWidget(self.frame_14)
        self.frame_15 = QtWidgets.QFrame(self.frame_19)
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_17.setContentsMargins(50, -1, 50, -1)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.btn_cliente_9 = QtWidgets.QPushButton(self.frame_15)
        self.btn_cliente_9.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_9.setFont(font)
        self.btn_cliente_9.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_9.setObjectName("btn_cliente_9")
        self.horizontalLayout_17.addWidget(self.btn_cliente_9)
        self.verticalLayout_11.addWidget(self.frame_15)
        self.verticalLayout_11.setStretch(0, 5)
        self.verticalLayout_11.setStretch(1, 2)
        self.horizontalLayout_16.addWidget(self.frame_19)
        self.horizontalLayout_16.setStretch(0, 5)
        self.horizontalLayout_16.setStretch(1, 4)
        self.horizontalLayout_3.addWidget(self.frame_pos_container)
        self.page_option.addWidget(self.page_pos)
        self.page_consulta = QtWidgets.QWidget()
        self.page_consulta.setStyleSheet("background-color: rgb(236, 240, 252)")
        self.page_consulta.setObjectName("page_consulta")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_consulta)
        self.horizontalLayout_7.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_4 = QtWidgets.QFrame(self.page_consulta)
        self.frame_4.setStyleSheet("#frame_4 , #frame_5 {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"\n"
"}\n"
"\n"
"QLabel{\n"
"    border: none;\n"
"    /*    border-bottom: 2px solid rgb(26, 70, 141);*/\n"
"    color:rgb(26, 70, 141);\n"
"    padding: 2px;\n"
"\n"
"}\n"
"#label_7 , #label_8 , #label_10 , #label_14 , #label_16 , #label_17 , #label_19 {\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_5.setContentsMargins(9, 9, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setStyleSheet("#frame_5{\n"
"border-top: 1px solid rgb(26,70,141);\n"
"}\n"
"QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"\n"
"\n"
"#label_13 , #label_15 , #label_18 , #label_20 , #label_9 {\n"
"    \n"
"    \n"
"    color:rgb(26, 70, 141);\n"
"    background-color: rgb(236, 240, 252);\n"
"\n"
"} \n"
"\n"
"")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_17.setContentsMargins(100, 10, 100, 35)
        self.verticalLayout_17.setSpacing(7)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_7 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_17.addWidget(self.label_7)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.frame_5)
        self.lineEdit_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_10.setInputMask("")
        self.lineEdit_10.setMaxLength(30)
        self.lineEdit_10.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.verticalLayout_17.addWidget(self.lineEdit_10)
        self.label_8 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_17.addWidget(self.label_8)
        self.label_18 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_17.addWidget(self.label_18)
        self.label_10 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_17.addWidget(self.label_10)
        self.label_20 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_17.addWidget(self.label_20)
        self.label_17 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_17.addWidget(self.label_17)
        self.label_9 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_17.addWidget(self.label_9)
        self.label_19 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_17.addWidget(self.label_19)
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_17.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_17.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_17.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_17.addWidget(self.label_16)
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_5)
        self.textBrowser.setMinimumSize(QtCore.QSize(0, 50))
        self.textBrowser.setStyleSheet("border: 1px solid rgb(26, 70, 141);\n"
"/*background-color: rgb(255, 255, 255);")
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout_17.addWidget(self.textBrowser)
        self.verticalLayout_5.addWidget(self.frame_5)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(100, -1, 100, 20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_cliente_3 = QtWidgets.QPushButton(self.frame_4)
        self.btn_cliente_3.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_3.setFont(font)
        self.btn_cliente_3.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_3.setObjectName("btn_cliente_3")
        self.verticalLayout_2.addWidget(self.btn_cliente_3)
        self.verticalLayout_5.addLayout(self.verticalLayout_2)
        self.horizontalLayout_7.addWidget(self.frame_4)
        self.page_option.addWidget(self.page_consulta)
        self.page_config = QtWidgets.QWidget()
        self.page_config.setStyleSheet("background-color: rgb(236, 240, 252)")
        self.page_config.setObjectName("page_config")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.page_config)
        self.horizontalLayout_5.setContentsMargins(25, 25, 25, 25)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame = QtWidgets.QFrame(self.page_config)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet("QFrame{\n"
"\n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"}\n"
"\n"
"QLabel{\n"
"    \n"
"    color: rgb(106, 106, 106);\n"
"}\n"
"\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setStyleSheet("#frame_2{\n"
"border-top: 1px solid rgb(26,70,141);\n"
"\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_3.setContentsMargins(200, 30, 200, 50)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_9.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_9.setFont(font)
        self.lineEdit_9.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_9.setInputMask("")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setMaxLength(10)
        self.lineEdit_9.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_9.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.verticalLayout_3.addWidget(self.lineEdit_9)
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(0, 50))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"paddin-right: 100px;\n"
"\n"
"")
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setMaxLength(10)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.frame_2)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setStyleSheet("border: none;\n"
"border-bottom: 2px solid rgb(26, 70, 141);\n"
"color:rgb(26, 70, 141);\n"
"padding: 2px;\n"
"\n"
"")
        self.lineEdit_7.setInputMask("")
        self.lineEdit_7.setMaxLength(6)
        self.lineEdit_7.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_7.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.verticalLayout_3.addWidget(self.lineEdit_7)
        self.verticalLayout_4.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_6.setContentsMargins(50, 5, 50, 5)
        self.horizontalLayout_6.setSpacing(30)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btn_cliente_2 = QtWidgets.QPushButton(self.frame_3)
        self.btn_cliente_2.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_cliente_2.setFont(font)
        self.btn_cliente_2.setStyleSheet("QPushButton{\n"
"\n"
"border:none;\n"
"color: white;\n"
"background-color:rgb(26, 70, 141);\n"
"border-radius: 10px 10px;\n"
"\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"/*border:none;*/\n"
"color: rgb(26, 70, 141);\n"
"background-color: #fffffffff;\n"
"border-radius: 10px 10px;\n"
"border: 2px solid rgb(26, 70, 141);\n"
"font-size: 20px;\n"
"\n"
"\n"
"}\n"
"")
        self.btn_cliente_2.setObjectName("btn_cliente_2")
        self.horizontalLayout_6.addWidget(self.btn_cliente_2)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.verticalLayout_4.setStretch(0, 5)
        self.verticalLayout_4.setStretch(1, 1)
        self.horizontalLayout_5.addWidget(self.frame)
        self.page_option.addWidget(self.page_config)
        self.verticalLayout.addWidget(self.page_option)
        self.stackedWidget.addWidget(self.page_main)
        self.horizontalLayout_12.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        self.page_option.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "IRON FITNESS"))
        self.label_2.setText(_translate("MainWindow", "Login"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Usuario"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Contraseña"))
        self.pushButton.setText(_translate("MainWindow", "Entrar"))
        self.btn_facebook.setText(_translate("MainWindow", "f"))
        self.btn_twitter.setText(_translate("MainWindow", "t"))
        self.btn_instagram.setText(_translate("MainWindow", "c"))
        self.btn_in.setText(_translate("MainWindow", "i"))
        self.label_logo.setText(_translate("MainWindow", "IRON FITNESS"))
        self.btn_inicio.setText(_translate("MainWindow", "INICIO"))
        self.bnt_registro.setText(_translate("MainWindow", "REGISTRO"))
        self.btn_pos.setText(_translate("MainWindow", "POS"))
        self.btn_pos_2.setText(_translate("MainWindow", "CONSULTA"))
        self.bnt_config.setText(_translate("MainWindow", "CONFIG"))
        self.label_36.setText(_translate("MainWindow", "0"))
        self.label_37.setText(_translate("MainWindow", "TOTAL REGISTRADOS"))
        self.label_38.setText(_translate("MainWindow", "0"))
        self.label_39.setText(_translate("MainWindow", "TOTAL ACTIVOS"))
        self.label_40.setText(_translate("MainWindow", "0"))
        self.label_41.setText(_translate("MainWindow", "TOTAL NO ACTIVOS"))
        self.label_42.setText(_translate("MainWindow", "0"))
        self.label_43.setText(_translate("MainWindow", "NUEVOS REGISTROS"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID_cliente"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "APELLIDO"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "FIN MENBRESIA"))
        self.lineEdit_15.setPlaceholderText(_translate("MainWindow", "ID_cliente"))
        self.btn_cliente_7.setText(_translate("MainWindow", "BUSCAR"))
        self.label_21.setText(_translate("MainWindow", "Numero de identificacion"))
        self.lineEdit_11.setPlaceholderText(_translate("MainWindow", "ID_cliente"))
        self.label_22.setText(_translate("MainWindow", "Nombre del cliente"))
        self.lineEdit_4.setPlaceholderText(_translate("MainWindow", "Nombre"))
        self.label_23.setText(_translate("MainWindow", "Apellido del cliente"))
        self.lineEdit_8.setPlaceholderText(_translate("MainWindow", "Apellido"))
        self.label_24.setText(_translate("MainWindow", "Numero de telefono"))
        self.lineEdit_6.setPlaceholderText(_translate("MainWindow", "+58 4125555555"))
        self.label_25.setText(_translate("MainWindow", "Descripion residencial"))
        self.btn_cliente_5.setText(_translate("MainWindow", "BUSCAR"))
        self.btn_cliente_6.setText(_translate("MainWindow", "REGISTRAR"))
        self.pushButton_6.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_12.setText(_translate("MainWindow", "Numero de identificacion"))
        self.lineEdit_12.setPlaceholderText(_translate("MainWindow", "ID_cliente"))
        self.label_26.setText(_translate("MainWindow", "Nombre y apellido:"))
        self.label_27.setText(_translate("MainWindow", ""))
        self.label_29.setText(_translate("MainWindow", "Numero de telefono"))
        self.label_28.setText(_translate("MainWindow", "+58 412999999"))
        self.label_30.setText(_translate("MainWindow", "Fin ultima menbresia paga "))
        self.label_31.setText(_translate("MainWindow", "0 - 0 - 0"))
        self.btn_cliente_4.setText(_translate("MainWindow", "BUSCAR"))
        self.label_32.setText(_translate("MainWindow", "Cantidad de Dias a pagar "))
        self.lineEdit_13.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "Fecha fin de la mebresia a pagar"))
        self.label_33.setText(_translate("MainWindow", "0 / 0 / 0 "))
        self.label_35.setText(_translate("MainWindow", "Descuento:"))
        self.lineEdit_14.setPlaceholderText(_translate("MainWindow", "0"))
        self.label_47.setText(_translate("MainWindow", "Monto:"))
        self.label_48.setText(_translate("MainWindow", "0$"))
        self.label_63.setText(_translate("MainWindow", "Total:"))
        self.label_62.setText(_translate("MainWindow", "0$"))
        self.btn_cliente_9.setText(_translate("MainWindow", "REALIZAR ABONO"))
        self.label_7.setText(_translate("MainWindow", "Numero de identificacion"))
        self.lineEdit_10.setPlaceholderText(_translate("MainWindow", "ID_cliente"))
        self.label_8.setText(_translate("MainWindow", "Nombre:"))
        self.label_18.setText(_translate("MainWindow", ""))
        self.label_10.setText(_translate("MainWindow", "Apellido:"))
        self.label_20.setText(_translate("MainWindow", ""))
        self.label_17.setText(_translate("MainWindow", "Fecha inicio de la menbresia:"))
        self.label_9.setText(_translate("MainWindow", ""))
        self.label_19.setText(_translate("MainWindow", "Fecha fin de la mebresia:"))
        self.label_13.setText(_translate("MainWindow", ""))
        self.label_14.setText(_translate("MainWindow", "Numero Telefonico: "))
        self.label_15.setText(_translate("MainWindow", ""))
        self.label_16.setText(_translate("MainWindow", "descripcion residencial:"))
        self.btn_cliente_3.setText(_translate("MainWindow", "BUSCAR"))
        self.label_6.setText(_translate("MainWindow", "Configuracion"))
        self.label_4.setText(_translate("MainWindow", "Precio del dia"))
        self.lineEdit_9.setPlaceholderText(_translate("MainWindow", "0$"))
        self.label_5.setText(_translate("MainWindow", "Precio de descuento por defecto"))
        self.lineEdit_3.setPlaceholderText(_translate("MainWindow", "0%"))
        self.label_11.setText(_translate("MainWindow", "Cambiar contraseña"))
        self.lineEdit_7.setPlaceholderText(_translate("MainWindow", "******"))
        self.btn_cliente_2.setText(_translate("MainWindow", "GUARDAR"))
import r_rc
